all:
  children:
    ungrouped: {}
    supergroup:
      children:
        host1: {}
        host2: {}
host1:
  hosts:
    host1:
      ansible_host: "3.67.91.164"
      ansible_ssh_private_key_file: "/Users/sturmkind/aws_ec2_key.pem"
      ansible_user: "ubuntu"
host2:
  hosts:
    host2:
      ansible_host: "3.64.12.64"
      ansible_ssh_private_key_file: "/Users/sturmkind/aws_ec2_key.pem"
      ansible_user: "ubuntu"
